### ISSUE TITLE
[TRACKER] Issues with sokol backend

### ISSUE THREAD

**Issue by Serkonda** [vlang/ui#183]
List of remaining problems with the new sokol backend.

- [ ] Textboxes do not accept input
- [ ] Images are not rendered
- [ ] Button text has wrong alignment (also in radio buttons)
- [ ] Sliders do not work

**Comment by serkonda7** [comment]
#### Done
- [x] Images are flipped over _(`users.v` `counter.v`)_
- [x] Images are not rendered _(`users.v` `counter.v`)_
- [x] Textboxes do not accept input
- [x] Wrong alignment of text in buttons
- [x] Missing text width calculation
